{
    "success": true,
    "data": [
        {
            "id": 197,
            "tenant_id": 1,
            "name": "Savanna Tech Solutions Ltd",
            "payroll_number_prefix": "ST",
            "kra_pin": "P051123456X",
            "nssf_number": "NSSF123456789",
            "nhif_number": "NHIF1234567",
            "legal_type": "LTD",
            "registration_number": "CPV/2021/12345",
            "physical_address": "UAP Tower, 17th Floor",
            "postal_address": "P.O. Box 1234",
            "postal_code_id": 100,
            "county_id": 1,
            "primary_phone": "+254712345678",
            "secondary_phone": "+254722334455",
            "official_email": "info@savannatech.com",
            "location": "Nairobi",
            "logo_url": "https://example.com/logo1.png",
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 30,
            "bank_id": 1,
            "bank_account_name": "Savanna Tech Solutions Ltd",
            "bank_account_number": "1234567890",
            "bank_branch": "KCB UAP Tower",
            "swift_code": null,
            "nssf_branch_code": "NSSFNAI",
            "nhif_branch_code": "NHIFNAI",
            "primary_administrator_id": 1,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "savannatech.com"
        },
        {
            "id": 198,
            "tenant_id": 1,
            "name": "Coastal Processors Ltd",
            "payroll_number_prefix": "CP",
            "kra_pin": "P051987654Z",
            "nssf_number": "NSSF987654321",
            "nhif_number": "NHIF7654321",
            "legal_type": "LTD",
            "registration_number": "CPV/2015/67890",
            "physical_address": "Mombasa Road, Plot 456",
            "postal_address": "P.O. Box 9876",
            "postal_code_id": 80100,
            "county_id": 2,
            "primary_phone": "+254712345678",
            "secondary_phone": "+254733112233",
            "official_email": "accounts@coastalprocessors.com",
            "location": "Mombasa",
            "logo_url": null,
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 30,
            "bank_id": 2,
            "bank_account_name": "Coastal Processors Ltd",
            "bank_account_number": "9876543210",
            "bank_branch": "Equity Mombasa",
            "swift_code": null,
            "nssf_branch_code": "NSSFMOM",
            "nhif_branch_code": "NHIFMOM",
            "primary_administrator_id": 2,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "coastalprocessors.com"
        },
        {
            "id": 199,
            "tenant_id": 2,
            "name": "Prestige Academy",
            "payroll_number_prefix": "PA",
            "kra_pin": "P052112233A",
            "nssf_number": "NSSF112233445",
            "nhif_number": "NHIF4455667",
            "legal_type": "School",
            "registration_number": "MS/2020/54321",
            "physical_address": "Kenyatta Avenue, Block B",
            "postal_address": "P.O. Box 5432",
            "postal_code_id": 20100,
            "county_id": 4,
            "primary_phone": "+254745678912",
            "secondary_phone": null,
            "official_email": "admin@prestigeacademy.sc.ke",
            "location": "Nakuru",
            "logo_url": "https://example.com/logo3.png",
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 25,
            "bank_id": 3,
            "bank_account_name": "Prestige Academy",
            "bank_account_number": "4567890123",
            "bank_branch": "Co-op Nakuru",
            "swift_code": null,
            "nssf_branch_code": "NSSFNAK",
            "nhif_branch_code": "NHIFNAK",
            "primary_administrator_id": 3,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "prestigeacademy.sc.ke"
        },
        {
            "id": 200,
            "tenant_id": 2,
            "name": "Lakeview Medical Hospital",
            "payroll_number_prefix": "LM",
            "kra_pin": "P052445566B",
            "nssf_number": "NSSF554466778",
            "nhif_number": "NHIF7788990",
            "legal_type": "LTD",
            "registration_number": "CPV/2018/11223",
            "physical_address": "Oginga Odinga Street",
            "postal_address": "P.O. Box 1122",
            "postal_code_id": 40100,
            "county_id": 3,
            "primary_phone": "+254770123456",
            "secondary_phone": "+254722334455",
            "official_email": "frontdesk@lakeviewmedical.org",
            "location": "Kisumu",
            "logo_url": null,
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 27,
            "bank_id": 4,
            "bank_account_name": "Lakeview Medical Hospital",
            "bank_account_number": "1122334455",
            "bank_branch": "Absa Kisumu",
            "swift_code": null,
            "nssf_branch_code": "NSSFKIS",
            "nhif_branch_code": "NHIFKIS",
            "primary_administrator_id": 4,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "lakeviewmedical.org"
        },
        {
            "id": 201,
            "tenant_id": 3,
            "name": "Highlands Farmers Co-op",
            "payroll_number_prefix": "HF",
            "kra_pin": "P052778899C",
            "nssf_number": "NSSF667788990",
            "nhif_number": "NHIF9988776",
            "legal_type": "Other",
            "registration_number": "CAC/2019/33445",
            "physical_address": "Nandi Road, Eldoret",
            "postal_address": "P.O. Box 3344",
            "postal_code_id": 30100,
            "county_id": 5,
            "primary_phone": "+254754321098",
            "secondary_phone": "+254711223344",
            "official_email": "manager@highlandscoop.co.ke",
            "location": "Eldoret",
            "logo_url": "https://example.com/logo5.png",
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 26,
            "bank_id": 5,
            "bank_account_name": "Highlands Farmers Cooperative",
            "bank_account_number": "5566778899",
            "bank_branch": "NCBA Eldoret",
            "swift_code": null,
            "nssf_branch_code": "NSSFELD",
            "nhif_branch_code": "NHIFELD",
            "primary_administrator_id": 5,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "highlandscoop.co.ke"
        },
        {
            "id": 202,
            "tenant_id": 3,
            "name": "Speedy Cargo Logistics",
            "payroll_number_prefix": "SC",
            "kra_pin": "P051334455D",
            "nssf_number": "NSSF334455667",
            "nhif_number": "NHIF2233445",
            "legal_type": "LTD",
            "registration_number": "CPV/2017/44556",
            "physical_address": "Enterprise Road, Industrial Area",
            "postal_address": "P.O. Box 4455",
            "postal_code_id": 500,
            "county_id": 1,
            "primary_phone": "+254734567890",
            "secondary_phone": null,
            "official_email": "dispatch@speedycargo.co.ke",
            "location": "Nairobi",
            "logo_url": null,
            "currency": "KES",
            "payroll_schedule": "Bi-Monthly",
            "payroll_lock_date": null,
            "default_payday": 15,
            "bank_id": 6,
            "bank_account_name": "Speedy Cargo Logistics",
            "bank_account_number": "6677889900",
            "bank_branch": "Equity Industrial Area",
            "swift_code": null,
            "nssf_branch_code": "NSSFNAI",
            "nhif_branch_code": "NHIFNAI",
            "primary_administrator_id": 6,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "speedycargo.co.ke"
        },
        {
            "id": 203,
            "tenant_id": 4,
            "name": "Twiga Foods Ltd",
            "payroll_number_prefix": "TF",
            "kra_pin": "P051556677E",
            "nssf_number": "NSSF556677889",
            "nhif_number": "NHIF5544332",
            "legal_type": "LTD",
            "registration_number": "CPV/2022/55667",
            "physical_address": "Thika Road Mall, 2nd Floor",
            "postal_address": "P.O. Box 5566",
            "postal_code_id": 900,
            "county_id": 6,
            "primary_phone": "+254787654321",
            "secondary_phone": "+254700112233",
            "official_email": "bookings@twigafoods.com",
            "location": "Kiambu",
            "logo_url": "https://example.com/logo7.png",
            "currency": "KES",
            "payroll_schedule": "Weekly",
            "payroll_lock_date": null,
            "default_payday": 5,
            "bank_id": 7,
            "bank_account_name": "Twiga Foods Ltd",
            "bank_account_number": "7788990011",
            "bank_branch": "KCB Thika Road",
            "swift_code": null,
            "nssf_branch_code": "NSSFKIAM",
            "nhif_branch_code": "NHIFKIAM",
            "primary_administrator_id": 7,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "twigafoods.com"
        },
        {
            "id": 204,
            "tenant_id": 4,
            "name": "Njoroge & Advocates LLP",
            "payroll_number_prefix": "NA",
            "kra_pin": "P051998877F",
            "nssf_number": "NSSF998877665",
            "nhif_number": "NHIF1122334",
            "legal_type": "Partnership",
            "registration_number": "LSK/2023/00123",
            "physical_address": "ICEA Building, Chiromo Road",
            "postal_address": "P.O. Box 7788",
            "postal_code_id": 100,
            "county_id": 1,
            "primary_phone": "+254711334455",
            "secondary_phone": null,
            "official_email": "legal@njorogeadvocates.com",
            "location": "Nairobi",
            "logo_url": null,
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 28,
            "bank_id": 8,
            "bank_account_name": "Njoroge & Advocates LLP",
            "bank_account_number": "9900112233",
            "bank_branch": "Co-operative Bank Westlands",
            "swift_code": null,
            "nssf_branch_code": "NSSFNAI",
            "nhif_branch_code": "NHIFNAI",
            "primary_administrator_id": 8,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "njorogeadvocates.com"
        },
        {
            "id": 205,
            "tenant_id": 5,
            "name": "Uchumi Retail Stores",
            "payroll_number_prefix": "UR",
            "kra_pin": "P051665544G",
            "nssf_number": "NSSF665544332",
            "nhif_number": "NHIF6655443",
            "legal_type": "LTD",
            "registration_number": "CPV/2010/99887",
            "physical_address": "Tom Mboya Street",
            "postal_address": "P.O. Box 9988",
            "postal_code_id": 100,
            "county_id": 1,
            "primary_phone": "+254722665544",
            "secondary_phone": "+254733998877",
            "official_email": "customercare@uchumistores.com",
            "location": "Nairobi",
            "logo_url": "https://example.com/logo9.png",
            "currency": "KES",
            "payroll_schedule": "Bi-Monthly",
            "payroll_lock_date": null,
            "default_payday": 20,
            "bank_id": 9,
            "bank_account_name": "Uchumi Retail Stores Ltd",
            "bank_account_number": "4455667788",
            "bank_branch": "Absa Tom Mboya",
            "swift_code": null,
            "nssf_branch_code": "NSSFNAI",
            "nhif_branch_code": "NHIFNAI",
            "primary_administrator_id": 9,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "uchumistores.com"
        },
        {
            "id": 206,
            "tenant_id": 5,
            "name": "Maasai Safari Adventures",
            "payroll_number_prefix": "MS",
            "kra_pin": "P052334455H",
            "nssf_number": "NSSF223344556",
            "nhif_number": "NHIF4433221",
            "legal_type": "Sole_Proprietor",
            "registration_number": "BN/2023/55667",
            "physical_address": "Maasai Mara Road",
            "postal_address": "P.O. Box 3344",
            "postal_code_id": 20500,
            "county_id": null,
            "primary_phone": "+254755443322",
            "secondary_phone": "+254766554433",
            "official_email": "book@maasaisafari.com",
            "location": "Narok",
            "logo_url": null,
            "currency": "KES",
            "payroll_schedule": "Monthly",
            "payroll_lock_date": null,
            "default_payday": 28,
            "bank_id": 10,
            "bank_account_name": "Maasai Safari Adventures",
            "bank_account_number": "3344556677",
            "bank_branch": "NCBA Narok",
            "swift_code": null,
            "nssf_branch_code": "NSSFNAR",
            "nhif_branch_code": "NHIFNAR",
            "primary_administrator_id": 10,
            "is_active": 1,
            "created_at": "2025-09-20 23:25:41",
            "updated_at": "2025-09-20 23:25:41",
            "domain": "maasaisafari.com"
        }
    ],
    "message": "Organizations fetched successfully",
    "metadata": {
        "page": 1,
        "limit": 10,
        "total": 25,
        "total_pages": 3,
        "dev_mode": true
    }
}